### PR TITLE
add abap ui for generation

### PR DESCRIPTION
**Pull request by colbyhemond**

### CODE REVIEW

**Comment by colbyhemond** [comment]
@larshp it looks like the checks are failing because of `AT SELECTION SCREEN ...`. Is there a replacement for this, or can these checks be ignored in this case?

**Comment by larshp** [comment]
as for use-case,

I see users running https://abap-openapi.github.io/web-openapi-client/ for ad-hoc generation, nothing to install or maintain for users => easy

Alternatively running the generation in a CI/CD pipeline keeping the implementation/scaffolding up to date via an automated workflow

**Comment by larshp** [comment]
@colbyhemond if you fix the CI findings, then the code can be merged. Tho, I think its the wrong approach, its much easier for users just to open https://abap-openapi.github.io/web-openapi-client/, and automation is required from my perspective

**Comment by larshp** [comment]
closing, feel free to open new PR which passes CI

**Pull request closed without merging**
